DT-6371: Use grapQL instead of rest
HSLdevcom/OTPQA pull request #33
Opened 2024-09-02 06:40 UTC by Antiik91

2024-09-02 11:56 UTC, vesameskanen requested changes
otpprofiler_json.py seems to work - test ratio value looks sensible, but the tool outputs:

reittiopas.hsl.fi
TEST DATE: 2024-09-09 14:00
profile=False
test count=200
total: 200.0 failed: 0 none: 7 ratio: 0.035

failed: 0 seems incorrect. In prod dataloading the same log looks like:
total: 200.0 failed: 8 none: 0 ratio: 0.04

Also, the code processes some parameter data which is no longer passed to otp requests. I suggest cleaning  dead code away. Let's use default transit requests, with arriveBy variation. Walkspeed etc can be removed.

2024-09-02 11:56 UTC, vesameskanen commented on otpprofiler.py
> +                after: $after,
Paging parameters are not set anywhere, so remove them. 

Currently query ignores 'arriveBy' selection from the request definitions. Please take it into account.

2024-09-02 11:56 UTC, vesameskanen commented on otpprofiler.py
> +import datetime
This PR adds new deps into OTPQA. Those should be installed here: 
https://github.com/HSLdevcom/OpenTripPlanner-data-container/blob/v3/otp-data-tools/build-otp-data-tools.sh

2024-09-19 10:06 UTC, optionsome commented on otpprofiler.py
> +        offset_datetime = offset_datetime[:-2] + ":" + offset_datetime[-2:]
Is this just converting the time into ISO format? I think the datetime has some built-in method to output the time in that format.

2024-09-19 10:06 UTC, optionsome commented on otpprofiler.py
> +        }
Btw what would happen if we added `transitOnly: !direct_only` here? It could make sense since we want to test that the transit network works.

2024-09-25 06:29 UTC, Antiik91 commented on otpprofiler.py
> +        }
With my current test setup it does not change the result at all.

2024-11-05 13:23 UTC, merged